name: Swift-XCode12

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1.2.1
      with:
        project: TomatoKitchenTimer.xcodeproj
        scheme: TomatoKitchenTimer
        destination: platform=macOS
        action: test


